title: About Me
logo: /assets/img/selfie.jpeg
description: Ph.D.-bound Systems Enthusiast | UMich & SJTU Alum-to-be
# show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
repository: keke1022/portfolio
